### ISSUE TITLE
Questions on the dataset for DHN and training process

### ISSUE THREAD

**Issue by haruishi43** [yihongXU/deepMOT#32]
Hi, thanks for uploading the training code for DHN!
I have some questions for DHN:
1. How did you create the train and test split? On the paper, it said that you had 114,483 and 17,880 for training and testing splits respectively, but when I ran your code, the validation and train lengths for 1 batch size were 1998 and 11870. 
2. While training, I saw precision and recall were steadily increasing, but weighted accuracies were 0.00% throughout. Could there be a bug in your code?

**Comment by yihongXU** [comment]
Hi, thank for testing our work!
(1) the printed number "1998" and "11870" are actually # of batches. Because the matrices are of varying, I randomly packed matrices of a same size and saved it to a same .npy (of <=10 in a batch). If you count the # of elements in the batches. You should get  1998 and 11870.

(2) I tested with my singularity image (like docker), it printed the wa correctly:
![image](https://user-images.githubusercontent.com/18198885/80638427-b23c2100-8a60-11ea-9ccb-f88d1dca8b20.png)
It was a problem of pytorch version of line 506 and 507 in deepmot/train_DHN/utils.py:
```python
 num_tp = float(((predicted[b, :, :] == target[b, :, :]) + (target[b, :, :] == 1.0)).eq(2).sum())
 num_tn = float(((predicted[b, :, :] == target[b, :, :]) + (target[b, :, :] == 0.0)).eq(2).sum())
```
in higher version of pytorch, it seems that it will not convert bool to float automatically, so ".eq(2)" will always be False and num_tp and num_tn will be always zero.

The bug can be fixed by adding ".float()":
```python
 num_tp = float(((predicted[b, :, :] == target[b, :, :]).float() + (target[b, :, :] == 1.0).float()).eq(2).sum())
 num_tn = float(((predicted[b, :, :] == target[b, :, :]).float() + (target[b, :, :] == 0.0).float()).eq(2).sum())
```

Thank you for pointing out this bug.

**Comment by haruishi43** [comment]
Thanks for your reply @yihongXU !

1. I see, so there's at most 10 in each of the batches, that makes sense. Did you hand-pick the matrices so the dataset would not use too much GPU memory?

2. Thank you for debugging! It was my bad, I didn't use singularity but followed tracking_wo_bw's instructions and forgot to use an older version of pytorch.

**Comment by yihongXU** [comment]
Hi， 
I randomly pick ~10 and made them a batch. Why 10, for GPU memory issue, but you can reorganize them according to your gpus. And you can also use your own data since the given one are all from MOT.
