### ISSUE TITLE
Not able to run the Singularity image

### ISSUE THREAD

**Issue by Cram3r95** [yihongXU/deepMOT#37]
When I try to run the provided singularity image (tracker.sif) I get the following error:

ERROR  : Unknown image format/type: tracker.sif
ABORT  : Retval = 255

What can I do?

**Comment by yihongXU** [comment]
Hi,
It might due to the singularity version that you use. I've checked and I am using singularity version 3.5.3. It works fine.
For more installation details, you can go and check, I think with version > 3.0, you can run it without errors.
[https://sylabs.io/guides/3.3/user-guide/installation.html#install-on-linux](url)
